### PR TITLE
docs(sample): Add sample for Native Image support in Pub/Sub

### PR DESCRIPTION
**Pull request by mpeddada1**
This PR copies over the Pub/Sub sample, Setup Instructions and README for native image support from [GoogleCloudPlatform/native-image-support-java](https://github.com/GoogleCloudPlatform/native-image-support-java/tree/master/native-image-samples/native-image-samples-client-library/pubsub-sample). It also adds an integration test that can be run as a native image.

Calling `mvn package -Pnative -DskipTests` builds the native image for the application and calling `mvn test -Pnative` runs the test as a native image. 

For more information: https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#configuration

### CODE REVIEW

**Comment by anguillanneuf** [comment]
@mpeddada1 I'm seeing similar PRs for other products but I'm not aware of the context. Could you tell me a bit more about these samples?

**Review by anguillanneuf — COMMENTED** [review]
Can someone tell me a bit more about this?

**Comment by mpeddada1** [comment]
> @mpeddada1 I'm seeing similar PRs for other products but I'm not aware of the context. Could you tell me a bit more about these samples?

Thanks for the question! This is part of the work to move all development away from the old native image support repository https://github.com/GoogleCloudPlatform/native-image-support-java into the googleapis/. To that end, as you may have noticed, we are trying to relocating all the [samples](https://github.com/GoogleCloudPlatform/native-image-support-java/tree/master/native-image-samples) from the old repo into the respective libraries in googleapis/.

**Comment by anguillanneuf** [comment]
Thanks @mpeddada1. One more question, who will be responsible for updating these samples?

**Comment by mpeddada1** [comment]
> Thanks @mpeddada1. One more question, who will be responsible for updating these samples? I don't mean the pom.xml but the samples themselves. At some point they will become outdated.

That's a good question @anguillanneuf! We'll maintain any parts of the sample that are native-image/GraalVM specific or require any knowledge of GraalVM (such as the setup instructions, addressing any issues related to Native Image compilation, keeping the GraalVM versions up-to-date). However, library maintainers would be better suited to address more product-specific aspects.

**Review by anguillanneuf — APPROVED** [review]

**Pull request merged**
