### PR TITLE
samples: migrate publisher samples and add tests

### PR DESCRIPTION
**Pull request by anguillanneuf**
Migrate publisher samples, currently living in [`google-cloud-java`](https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets) (no tests were written for them) and [`java-docs-samples`](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/pubsub/cloud-client) (incomplete set of samples), here.  This is **part 1 of 5** of Pub/Sub Java samples migration. 

Added tests for them too.  

Part 1: migrate publisher samples
Part 2: migrate subscriber samples
Part 3: migrate topic admin samples
Part 4: migrate subscription admin samples
Part 5: migrate iam, emulator, and other miscellaneous samples
Part 6: update docs. add notes to old samples.

### CODE REVIEW

**Comment by anguillanneuf** [comment]
@hongalex The test failure is caused by something else. In case you are wondering, tests on the master branch are also experiencing this error (I'm not sure how to fix it yet): 

```
[ERROR] Failed to execute goal com.coveo:fmt-maven-plugin:2.10:check (default-cli) on project pubsub-install-without-bom: Execution default-cli of goal com.coveo:fmt-maven-plugin:2.10:check failed: An API incompatibility was encountered while executing com.coveo:fmt-maven-plugin:2.10:check: java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/FormatterException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by anguillanneuf** [comment]
@elharo I'm at a loss trying to fix "ci / lint (pull_request)", which is also failing on the master branch. Can I pick your brain?

**Comment by elharo** [comment]
This is not my repo. Who on the pubsub team is responsible for this?

**Comment by elharo** [comment]
Check the logs:

2020-06-04T16:09:26.0938802Z [ERROR] Failed to execute goal com.coveo:fmt-maven-plugin:2.10:check (default-cli) on project pubsub-install-without-bom: Execution default-cli of goal com.coveo:fmt-maven-plugin:2.10:check failed: An API incompatibility was encountered while executing com.coveo:fmt-maven-plugin:2.10:check: java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/FormatterException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java 


Looks like the format plugin wants a different Java version.

**Comment by anguillanneuf** [comment]
Discussed with @chingor13. Lint failure can be temporarily resolved by removing `enable-samples` profile from the root pom.xml.

**Comment by anguillanneuf** [comment]
Ping today's FixIt Java reps for review: @kolea2 @lesv @BenWhitehead

**Pull request merged**
