### PR TITLE
chore: disable the Owl Bot post-processor

### PR DESCRIPTION
**Pull request by diegomarquezp**
via deleting .OwlBot.lock.yaml ([context](https://docs.google.com/document/d/1wrpyBtphdenM3BNelcnpBKGADYrGJUo686HXvSA0h-0/edit?pli=1&tab=t.0#bookmark=kix.914gcjvdwt3u))

### CODE REVIEW

**Comment by diegomarquezp** [comment]
`do not merge` until https://github.com/googleapis/java-pubsub/pull/2104 is merged

**Review by michaelpri10 — APPROVED** [review]

**Pull request merged**
