### PR TITLE
feat: Improve TopicName.parse ValidationException message

### LINKED ISSUE #1480: TopicAdminClient UnauthenticatedException When Settings Endpoints
From https://github.com/GoogleCloudPlatform/pubsub/issues/333:

Hi,
I've found an issue when settings TopicAdminClient with endpoint.

**Current behavior:** 
- When i try to set TopicAdminClient  with credentials out of a json(String) and endpoint different then the global "pubsub.googleapis.com" end point i get an UnauthenticatedException. 
- When i use ADC authentication and set the environment variable GOOGLE_APPLICATION_CREDENTIALS to point to a json file with the same content i can set to all endpoints with no errors.
- When i try to set TopicAdminClient  with credentials out of a json(String) and use the global endpoint pubsub.googleapis.com" i get no errors.

**Expected behavior:** 
To be able to use both authentication ways and set any endpoint without encountering any error. 

**Example:**
```
...
ServiceAccountCredentials cred = ServiceAccountCredentials
              .fromStream(new ByteArrayInputStream(jsonCredentials.getBytes()));  // json as String

CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(cred); 

TopicAdminSettings topicAdminSettings = TopicAdminSettings.newBuilder()
                                 .setCredentialsProvider(credentialsProvider)   // credentials out of given json file
                                 .setEndpoint(endpoint)                         // endpoint different then global endpoint
                                 .build();

TopicAdminClient topicAdminClient = TopicAdminClient.create(topicAdminSettings);

topicAdminClient.getTopic(someTopic);
```

the code above produce the following exception:
`com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.'`

### LINKED ISSUE #1504: TopicName.parse could throw a more detailed ValidationException
Recently I faced an issue when using the `Topic.parse(String formattedString)` method, because the String being used was an environment variable defined within a pod.
I could've been faster in resolving the issue, if the `formattedString` originating from the environment variable would be printed out as part of the ValidationException's message.

Current behavior:

The message `TopicName.parse: formattedString not in valid format` is shown.

```java
throw new ValidationException("TopicName.parse: formattedString not in valid format");
```

Expected / desired behavior:

The message `TopicName.parse: formattedString (${actual value of formattedString}) not in valid format` is shown.

```java
throw new ValidationException(
        "TopicName.parse: formattedString (%s) not in valid format", formattedString);
```

### PR DESCRIPTION
**Pull request by SimonScholz**
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-pubsub/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes googleapis/google-cloud-java#13054  ☕️

### CODE REVIEW

**Review by maitrimangal — APPROVED** [review]

**Comment by SimonScholz** [comment]
The failure there sounds like a flaky test to me.
I cannot imagine how this change would have an impact on it.
And I've run the com.google.cloud.pubsub.v1.SubscriberTest#testStreamAckDeadlineIsSetCorrectly method locally on my machine and it worked.
What about these "Kokoro" runs? How will those be triggered?

**Comment by SimonScholz** [comment]
Pushed once gain to re-trigger the build.

**Comment by SimonScholz** [comment]
@maitrimangal can you re-trigger the build somehow?

**Review by maitrimangal — APPROVED** [review]

**Comment by maitrimangal** [comment]
Sorry, Actually realized that this is actually an auto generated file, so cannot approve this.

**Comment by SimonScholz** [comment]
@maitrimangal how is this file being generated. Can you elaborate on this a bit? Then I could try to do the fix in the right place.

**Comment by maitrimangal** [comment]
https://github.com/googleapis/java-pubsub/blob/8ded11041c63f1f75f0612c081ba6b476b6b89b8/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/TopicName.java#L31 this is an auto-generated class stated here

**Pull request closed without merging**
